kind: Deployment
apiVersion: apps/v1
metadata:
  name: flaskhello
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flaskhello
        image: pazmariano/traackr:v0.1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskhello
spec:
  ports:
  - name: web
    targetPort: 5000
    protocol: TCP
    port: 80
  selector:
    app: flask
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flaskhello
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: flaskhello.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: flaskhello
          servicePort: web
